package com.erp.reimbursement.service;
import com.erp.reimbursement.dto.AuthDtos.*; import com.erp.reimbursement.entity.*; import com.erp.reimbursement.enums.Role; import com.erp.reimbursement.exception.ApiException; import com.erp.reimbursement.repository.*; import com.erp.reimbursement.security.JwtService; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import java.time.*; import java.util.*; import java.util.concurrent.*;
@Service public class AuthService {private final UserRepository users;private final DepartmentRepository departments;private final PasswordEncoder encoder;private final JwtService jwt;private final Map<String,String> otps=new ConcurrentHashMap<>(); public AuthService(UserRepository u,DepartmentRepository d,PasswordEncoder e,JwtService j){users=u;departments=d;encoder=e;jwt=j;}
 public LoginResponse login(LoginRequest r){String identifier = r.email() == null ? "" : r.email().trim();
 User u=users.findByEmailIgnoreCaseOrUsernameIgnoreCase(identifier,identifier).orElseGet(() -> users.findFirstByMobile(identifier).orElseThrow(()->new ApiException("Invalid email, username, mobile number, or password")));if(u.getRole()!=r.role()||!u.isActive()||!encoder.matches(r.password(),u.getPassword()))throw new ApiException("Invalid email, username, mobile number, password, or selected role.");String token=jwt.generate(u.getUsername(),u.getRole().name());return new LoginResponse(token,u.getUsername(),u.getRole().name(),u.getEmployeeId(),u.getFullName(),u.getFirstName(),u.getLastName(),u.getEmail(),u.getDepartment()==null?null:u.getDepartment().getName(),u.getDesignation());}
 public User signup(SignupRequest r){if(users.findByEmailIgnoreCase(r.email()).isPresent()||users.findByEmployeeId(r.employeeId()).isPresent())throw new ApiException("Email or employee ID already exists");Department d=departments.findByNameIgnoreCase(r.department()).orElseThrow(()->new ApiException("Department not found"));User u=new User();u.setEmployeeId(r.employeeId());u.setFirstName(r.firstName());u.setLastName(r.lastName());u.setEmail(r.email().toLowerCase());u.setUsername(r.email().toLowerCase());u.setPassword(encoder.encode(r.password()));u.setDateOfBirth(r.dateOfBirth());u.setDepartment(d);u.setMobile(r.mobile());u.setAlternateMobile(r.alternateMobile());u.setDesignation("Employee");u.setRole(Role.EMPLOYEE);return users.save(u);}
 public void sendOtp(OtpRequest r){User u=users.findByEmailIgnoreCase(r.email()).orElseThrow(()->new ApiException("No account found"));if(!Objects.equals(u.getMobile(),r.mobile()))throw new ApiException("Email and mobile do not match");String otp=String.format("%06d",new Random().nextInt(1_000_000));otps.put(r.email().toLowerCase(),otp);System.out.println("DEMO OTP for "+r.email()+": "+otp);}
 public void reset(ResetPasswordRequest r){String saved=otps.get(r.email().toLowerCase());if(saved==null||!saved.equals(r.otp()))throw new ApiException("Invalid or expired OTP");User u=users.findByEmailIgnoreCase(r.email()).orElseThrow(()->new ApiException("No account found"));u.setPassword(encoder.encode(r.newPassword()));users.save(u);otps.remove(r.email().toLowerCase());}
}
