package com.erp.reimbursement.enums;
public enum ClaimStatus { SUBMITTED, PENDING_MANAGER_APPROVAL, MANAGER_APPROVED, PENDING_FINANCE_VERIFICATION, FINANCE_APPROVED, PENDING_PAYMENT, PAID, REJECTED }
